# Generated by Django 5.1.5 on 2025-02-04 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChuzoReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('price', models.PositiveIntegerField()),
                ('price_quantity_ratio', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('cheese_review', models.TextField(null=True)),
                ('cheese_quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('protein_review', models.TextField(null=True)),
                ('potato_review', models.TextField(null=True)),
                ('tartar_review', models.TextField(null=True)),
                ('pineapple_review', models.TextField(null=True)),
                ('grille_review', models.TextField(null=True)),
                ('special_sauce_review', models.TextField(null=True)),
                ('bollo_review', models.TextField(null=True)),
                ('photo_url', models.TextField(null=True)),
                ('visited_at', models.DateTimeField()),
                ('additional_comments', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
